// <auto-generated />
using System;
using Api_Exec_2.Context.Service;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Exec_2.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240510021430_CorrecaoMigrationInicial")]
    partial class CorrecaoMigrationInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api_Exec_2.Model.Conta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CNPJ")
                        .IsRequired()
                        .HasMaxLength(18)
                        .HasColumnType("varchar(18)");

                    b.Property<int?>("ContatoPrimarioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CNPJ")
                        .IsUnique();

                    b.HasIndex("ContatoPrimarioId")
                        .IsUnique();

                    b.ToTable("Contas");
                });

            modelBuilder.Entity("Api_Exec_2.Model.Contato", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("varchar(14)");

                    b.Property<int?>("ContaId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("SobreNome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("CPF")
                        .IsUnique();

                    b.HasIndex("ContaId");

                    b.ToTable("Contatos");
                });

            modelBuilder.Entity("Api_Exec_2.Model.Conta", b =>
                {
                    b.HasOne("Api_Exec_2.Model.Contato", "ContatoPrimario")
                        .WithOne()
                        .HasForeignKey("Api_Exec_2.Model.Conta", "ContatoPrimarioId");

                    b.OwnsOne("Api_Exec_2.Model.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("ContaId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("CEP")
                                .HasMaxLength(9)
                                .HasColumnType("varchar(9)");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<int?>("Numero")
                                .HasColumnType("int");

                            b1.HasKey("ContaId");

                            b1.ToTable("Contas");

                            b1.WithOwner()
                                .HasForeignKey("ContaId");
                        });

                    b.Navigation("ContatoPrimario");

                    b.Navigation("Endereco");
                });

            modelBuilder.Entity("Api_Exec_2.Model.Contato", b =>
                {
                    b.HasOne("Api_Exec_2.Model.Conta", "Conta")
                        .WithMany("ListaContatos")
                        .HasForeignKey("ContaId");

                    b.OwnsOne("Api_Exec_2.Model.Endereco", "Endereco", b1 =>
                        {
                            b1.Property<int>("ContatoId")
                                .HasColumnType("int");

                            b1.Property<string>("Bairro")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("CEP")
                                .HasMaxLength(9)
                                .HasColumnType("varchar(9)");

                            b1.Property<string>("Complemento")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<string>("Logradouro")
                                .HasMaxLength(150)
                                .HasColumnType("varchar(150)");

                            b1.Property<int?>("Numero")
                                .HasColumnType("int");

                            b1.HasKey("ContatoId");

                            b1.ToTable("Contatos");

                            b1.WithOwner()
                                .HasForeignKey("ContatoId");
                        });

                    b.Navigation("Conta");

                    b.Navigation("Endereco")
                        .IsRequired();
                });

            modelBuilder.Entity("Api_Exec_2.Model.Conta", b =>
                {
                    b.Navigation("ListaContatos");
                });
#pragma warning restore 612, 618
        }
    }
}
